### ISSUE TITLE
Design Admin Dashboard Screen-mmm-team-4

### ISSUE THREAD

**Issue by marawanxmamdouh** [ALCOpenSource/alc-MMSystem-admin#12]
Without bottom-navigation-bar it will add as an included layout

**Comment by sabete-dev** [comment]
I am working on it
![image](https://user-images.githubusercontent.com/83730256/201522001-dd8bc729-f26f-4ec7-be50-5a6a599cc780.png)

**Comment by marawanxmamdouh** [comment]
Solved https://github.com/marawanxmamdouh/alc-MMSystem-admin/commit/dd99b302eb33299c6688d05fada7b23808b583d8
