### ISSUE TITLE
Design Admin Notifications Screen-mmm-team-4

### ISSUE THREAD

**Issue by marawanxmamdouh** [ALCOpenSource/alc-MMSystem-admin#19]
- Without bottom-navigation-bar it will add as an included layout

- Please Make sure to use the RecyclerView and List Adapter.

**Comment by marawanxmamdouh** [comment]
Please Make sure to use the **RecyclerView** and **List Adapter**.

**Comment by NadaFeteiha** [comment]
I am working on it

**Comment by marawanxmamdouh** [comment]
Solved https://github.com/marawanxmamdouh/alc-MMSystem-admin/pull/19/
