### ISSUE TITLE
Design Admin Search MM Mentors Screen-mmm-team-4

### ISSUE THREAD

**Issue by marawanxmamdouh** [ALCOpenSource/alc-MMSystem-admin#22]
Please Make sure to use the **RecyclerView** and **List Adapter**.

**Comment by NadaFeteiha** [comment]
I am working on it.

**Comment by marawanxmamdouh** [comment]
Solved [implement admin MM programs, Search MM Mentors, and MM Tasks Screens #59](https://github.com/ALCOpenSource/alc-MMSystem-admin/pull/59)
