### ISSUE TITLE
Design Admin MM Report Screen-mmm-team-4

### ISSUE THREAD

**Issue by marawanxmamdouh** [ALCOpenSource/alc-MMSystem-admin#26]
Please Make sure to use the **RecyclerView** and **List Adapter**.

**Comment by NadaFeteiha** [comment]
I am working on it.

**Comment by marawanxmamdouh** [comment]
Solved https://github.com/marawanxmamdouh/alc-MMSystem-admin/pull/15

**Comment by marawanxmamdouh** [comment]
Solved https://github.com/marawanxmamdouh/alc-MMSystem-admin/pull/15/
